### PR TITLE
Convert to a V2 addon and drop support for Ember < 3.28

### PR DESCRIPTION
**Pull request by mansona**
Roughly speaking I ran `ember init -b @embroider/addon-blueprint --pnpm` to get this far, and then did some tweaking

Sure this is a little extreme but it's at least possible so we should consider it (maybe) 😂

### CODE REVIEW

**Review by jaredgalanis — APPROVED** [review]
🎉

**Comment by IgnaceMaes** [comment]
The callout images are not present, that seems unexpected?

https://deploy-preview-188--guidemaker-ember-template.netlify.app/release/examples/callouts

image

**Comment by IgnaceMaes** [comment]
Images look all good now with the latest Embroider version!

Only thing missing seems to be the icons:

image

**Review by IgnaceMaes — APPROVED** [review]
Looking good now!

**Pull request merged**
