### PR TITLE
feat: Use `ember-showdown-shikiji` for syntax highlighting

### PR DESCRIPTION
**Pull request by IgnaceMaes**
Switch to [ember-showdown-shikiji](https://github.com/IgnaceMaes/ember-showdown-shikiji) for syntax highlighting.

- Adds support for `.gjs` and `.gts` highlighting
- Shikiji is maintained and actively worked on compared to Prism
- Unlocks the opportunity for future improvements
  - e.g. https://shikiji.netlify.app/packages/twoslash

Preview: https://deploy-preview-168--guidemaker-ember-template.netlify.app/release/examples/syntax-highlighting

Can only be released as major due to the manual Fastboot config requirement and Node minimum version bump.

### CODE REVIEW

**Review by mansona — CHANGES_REQUESTED** [review]
So far so good 🎉 this looks amazing! I'm particularly happy that this is a drop-in replacement for ember-showdown-prism 😍 

One thing I notice is that we've lost support for the "ribbons" in the top of the examples 🤔 this is something that we explicitly had before to make sure that people knew what file type they were looking at quicker. Is this something that you could add to ember-showdown-shikiji?

**Comment by mansona** [comment]
Also I'm a tiny bit concerned about this line https://github.com/IgnaceMaes/ember-showdown-shikiji/blob/main/ember-showdown-shikiji/src/initializers/showdown-shikiji.ts#L16

My understanding of our showdown implementation was that it was only including grammars for languages that we had specified (this assumption could be wrong though 🤪). Shouldn't we only include a subset of languages that shikiji supports? How much of an impact on the bundle size does this change have?

**Comment by IgnaceMaes** [comment]
Concerning bundle sizes, I benchmarked the following:

<details>
<summary>`npm run build` on this branch:</summary>


```
Built project successfully. Stored in "dist/".
File sizes:
 - dist/assets/chunk.1147.674668433459a5be40bf.js: 4.34 KB (1.28 KB gzipped)
 - dist/assets/chunk.1216.f176b3750ea1ef4d3acc.js: 5.1 KB (1.73 KB gzipped)
 - dist/assets/chunk.123.53a8ad469b5cf34acc8f.js: 52.63 KB (14.1 KB gzipped)
 - dist/assets/chunk.1234.ffe9c31827b1fa8003e7.js: 25.34 KB (5.49 KB gzipped)
 - dist/assets/chunk.1258.acc014bd5d89458d5153.js: 55.36 KB (13.3 KB gzipped)
 - dist/assets/chunk.1298.69cf6d3b3dce075058e1.js: 1.46 KB (548 B gzipped)
 - dist/assets/chunk.1433.c185cec96290dee84444.js: 2.16 KB (834 B gzipped)
 - dist/assets/chunk.1449.ea2d83dcc5ed38b70473.js: 13.74 KB (3.38 KB gzipped)
 - dist/assets/chunk.1482.ce9642fde2efb7e9e8d0.js: 30.97 KB (5.01 KB gzipped)
 - dist/assets/chunk.1492.47458fa3b5872fd41c85.js: 15.62 KB (3.3 KB gzipped)
 - dist/assets/chunk.1538.fda72394c6d70000b6ad.js: 71.3 KB (11.36 KB gzipped)
 - dist/assets/chunk.1541.2c4e3a1314cbea45d8b9.js: 31.93 KB (5.21 KB gzipped)
 - dist/assets/chunk.1544.1405be9881fb589f07c3.js: 8.45 KB (2.46 KB gzipped)
 - dist/assets/chunk.156.c971d7ef6415c24963e5.js: 87.27 KB (10.9 KB gzipped)
 - dist/assets/chunk.1586.91856ebece4cc04d908f.js: 44.29 KB (6.98 KB gzipped)
 - dist/assets/chunk.1590.ef956812d3cb3684d292.js: 6.16 KB (1.33 KB gzipped)
 - dist/assets/chunk.1599.1857cb28133622065484.js: 24.7 KB (4.42 KB gzipped)
 - dist/assets/chunk.1677.32bbab99b2f641717e33.js: 3.65 KB (1.07 KB gzipped)
 - dist/assets/chunk.1688.f34c2067b2ceefa428a3.js: 20.18 KB (4.6 KB gzipped)
 - dist/assets/chunk.1706.2fc2ee30743cc56a1c13.js: 11.98 KB (2.78 KB gzipped)
 - dist/assets/chunk.1715.cc03495483e5db6cebe3.js: 16.28 KB (2.59 KB gzipped)
 - dist/assets/chunk.1737.d4936d93c0b25ac5c579.js: 3.86 KB (1.22 KB gzipped)
 - dist/assets/chunk.1755.7619f9d5a7e9fc19b713.js: 180.27 KB (17.94 KB gzipped)
 - dist/assets/chunk.178.fef93d035f969ebe9948.js: 1.52 KB (815 B gzipped)
 - dist/assets/chunk.1858.34988860af60c7622325.js: 75.15 KB (12.74 KB gzipped)
 - dist/assets/chunk.1867.d341d91c465ee20ae386.js: 7.13 KB (2.24 KB gzipped)
 - dist/assets/chunk.1902.c42a69236605df50b600.js: 25.28 KB (4.08 KB gzipped)
 - dist/assets/chunk.1924.40ecc02b5437e6f30ece.js: 1.47 KB (544 B gzipped)
 - dist/assets/chunk.2013.accf580b97c82bb1343b.js: 5.89 KB (1.68 KB gzipped)
 - dist/assets/chunk.2033.ddc22d1901b6ddf41552.js: 22.65 KB (7.53 KB gzipped)
 - dist/assets/chunk.2058.72812f2efc5e8b3d1d81.js: 4.02 KB (1.07 KB gzipped)
 - dist/assets/chunk.2143.9d24b0c4ede8ddcddb43.css: 2.55 KB (820 B gzipped)
 - dist/assets/chunk.2143.9d24b0c4ede8ddcddb43.js: 9.31 KB (5.21 KB gzipped)
 - dist/assets/chunk.2154.3d414b22de7f752edbe6.js: 66.57 KB (10.39 KB gzipped)
 - dist/assets/chunk.2160.c9a3e4700b0d4d1fad2a.js: 19.82 KB (4 KB gzipped)
 - dist/assets/chunk.2198.2e97f11e2ccbdc97002a.js: 52.39 KB (6.07 KB gzipped)
 - dist/assets/chunk.2212.a8d794a81e23250be590.js: 17.55 KB (3.23 KB gzipped)
 - dist/assets/chunk.2276.dce71d50306b322a9ae4.js: 3.7 KB (1.68 KB gzipped)
 - dist/assets/chunk.2297.ceda34d5f3d02017824d.js: 618.3 KB (48.64 KB gzipped)
 - dist/assets/chunk.2351.db32bcaed3bcc3ff287f.js: 3.91 KB (1.09 KB gzipped)
 - dist/assets/chunk.2352.bff4e6174ae9fdf43c0c.js: 26.46 KB (3.75 KB gzipped)
 - dist/assets/chunk.2652.518fbb44d15dbef72d71.js: 68.53 KB (9.62 KB gzipped)
 - dist/assets/chunk.2681.649f0df82c48e37b7e42.js: 27.66 KB (4.49 KB gzipped)
 - dist/assets/chunk.274.4d1b05ea39349d7010dc.js: 7.04 KB (1.51 KB gzipped)
 - dist/assets/chunk.2752.1e4882579291f1cd463e.js: 12.74 KB (3.02 KB gzipped)
 - dist/assets/chunk.277.4629860066bb0f709536.js: 20.13 KB (3.99 KB gzipped)
 - dist/assets/chunk.2788.272adf2e09aabe7e96a7.js: 10.44 KB (2.41 KB gzipped)
 - dist/assets/chunk.283.dbb84e5988dba443fad4.js: 41.89 KB (5.82 KB gzipped)
 - dist/assets/chunk.2857.61502ce8eb7d89c3b84c.js: 2.23 KB (756 B gzipped)
 - dist/assets/chunk.2944.612f731a53ff269a0729.js: 42.23 KB (7.47 KB gzipped)
 - dist/assets/chunk.2949.30b5633e9d88b8ec1cdf.js: 59.08 KB (5 KB gzipped)
 - dist/assets/chunk.2983.897cf8e7cbbfb70b1346.js: 14.87 KB (2.62 KB gzipped)
 - dist/assets/chunk.3.c6f522e986627c2e2515.js: 12.16 KB (4.96 KB gzipped)
 - dist/assets/chunk.3005.80a9940db4571d3e9347.js: 9.02 KB (2.13 KB gzipped)
 - dist/assets/chunk.3065.d2372b5778f96683f0ac.js: 35.3 KB (7.83 KB gzipped)
 - dist/assets/chunk.308.b3084f7a365749dbf80e.js: 42.23 KB (7.48 KB gzipped)
 - dist/assets/chunk.3188.79240d53cf0bd3a35e1e.js: 14.27 KB (3.05 KB gzipped)
 - dist/assets/chunk.3292.5a0f052d54e0a33fecf6.js: 29.02 KB (4.16 KB gzipped)
 - dist/assets/chunk.3299.93268e2c3a57af0b20f2.js: 3.15 KB (1.5 KB gzipped)
 - dist/assets/chunk.3304.60fa7ee8b4717d795c81.js: 8.08 KB (1.77 KB gzipped)
 - dist/assets/chunk.3640.5665f4f4cbe0c82abf74.js: 4.56 KB (1.5 KB gzipped)
 - dist/assets/chunk.3655.40fc867eda3dc54e9d8e.js: 13.52 KB (4.58 KB gzipped)
 - dist/assets/chunk.3656.74ab6139aca7a115b529.js: 14.94 KB (2.06 KB gzipped)
 - dist/assets/chunk.3662.22d27692a0f20e9175fa.js: 37.72 KB (8.04 KB gzipped)
 - dist/assets/chunk.3698.27516a6df3210d8a605d.js: 19.78 KB (4.01 KB gzipped)
 - dist/assets/chunk.3704.b5ed5a7ad398bd458dfe.js: 18.12 KB (3.93 KB gzipped)
 - dist/assets/chunk.3760.f4da87d8e204149b8d2c.js: 17.81 KB (3.14 KB gzipped)
 - dist/assets/chunk.3775.68846ae7525e12482b56.js: 5.9 KB (1.61 KB gzipped)
 - dist/assets/chunk.3873.76ef00cd8c39296a47bc.js: 10.93 KB (3.83 KB gzipped)
 - dist/assets/chunk.4051.78a8788ba01d43700a9b.js: 10.16 KB (2.93 KB gzipped)
 - dist/assets/chunk.4084.db67ea3fc10522bfdf28.js: 13.66 KB (3.09 KB gzipped)
 - dist/assets/chunk.4105.b22c10e1840beee12be9.js: 108.69 KB (29.84 KB gzipped)
 - dist/assets/chunk.415.3514536d6e10ef1772da.js: 5.77 KB (2.43 KB gzipped)
 - dist/assets/chunk.4173.58069831f1172f46c8ac.js: 6.79 KB (1.92 KB gzipped)
 - dist/assets/chunk.4184.24e5aa44e5c2321034d6.js: 1.47 KB (542 B gzipped)
 - dist/assets/chunk.4202.158f884196bf424b9875.js: 32.19 KB (5.46 KB gzipped)
 - dist/assets/chunk.4223.c84cdb568a2bf66d798c.js: 5.77 KB (1.4 KB gzipped)
 - dist/assets/chunk.4234.a04c6ae27ef69eff7a4a.js: 7.25 KB (2.3 KB gzipped)
 - dist/assets/chunk.4310.6b5908762fd3debad0bc.js: 36.29 KB (9.02 KB gzipped)
 - dist/assets/chunk.4460.4b180b1f79240a0c974f.js: 55.99 KB (11.8 KB gzipped)
 - dist/assets/chunk.4512.e3391c6fb1b29d10b58c.js: 812 B (497 B gzipped)
 - dist/assets/chunk.4525.2faf3f71bdb2946e24fa.js: 22.47 KB (3.44 KB gzipped)
 - dist/assets/chunk.4542.0104648196df774a27a0.js: 178.08 KB (17.89 KB gzipped)
 - dist/assets/chunk.4558.9dcc25a1a5c1559a7265.js: 54.35 KB (9.37 KB gzipped)
 - dist/assets/chunk.4679.12d408beaeffa695aa93.js: 7.44 KB (1.92 KB gzipped)
 - dist/assets/chunk.4691.82a414a633b03d2901df.js: 5.07 KB (1.37 KB gzipped)
 - dist/assets/chunk.4699.5b6e6fe68d627842e953.js: 12.88 KB (3.04 KB gzipped)
 - dist/assets/chunk.477.1d9f3af85949923724b7.js: 4.51 KB (852 B gzipped)
 - dist/assets/chunk.4796.68b34601bb7b1f1d4dbf.js: 12.8 KB (3.04 KB gzipped)
 - dist/assets/chunk.4831.e3118f2c86ce76c093ba.js: 29.22 KB (8.01 KB gzipped)
 - dist/assets/chunk.4868.e8749d57ec18652b9919.js: 37.18 KB (8 KB gzipped)
 - dist/assets/chunk.4963.96c2693aa6379453a3f3.js: 4.94 KB (1.24 KB gzipped)
 - dist/assets/chunk.5041.12e16aa36cf1fc0eff31.js: 77.45 KB (12.78 KB gzipped)
 - dist/assets/chunk.5137.0ae13269eca63316afc0.js: 17.81 KB (3.12 KB gzipped)
 - dist/assets/chunk.5159.d2cc47914c80da7b28e1.js: 6.2 KB (1.83 KB gzipped)
 - dist/assets/chunk.5180.704a20fed8fcb6023dbc.js: 7.74 KB (1.68 KB gzipped)
 - dist/assets/chunk.5246.34ee58e1abad796628a7.js: 3.6 KB (1.21 KB gzipped)
 - dist/assets/chunk.526.d4423a78c28cbaeb6e57.js: 93.45 KB (17.37 KB gzipped)
 - dist/assets/chunk.5330.066f0729fd07f1a0b7c1.js: 17.81 KB (3.12 KB gzipped)
 - dist/assets/chunk.5341.fa5a5adf2fff67178071.js: 100.57 KB (23.11 KB gzipped)
 - dist/assets/chunk.5369.815ccf88448277ee83db.js: 12.91 KB (3.94 KB gzipped)
 - dist/assets/chunk.5378.f33971710c25511818f2.js: 162.43 KB (30.3 KB gzipped)
 - dist/assets/chunk.5398.8e7eab8bc2a0ec39131f.js: 8.69 KB (1.86 KB gzipped)
 - dist/assets/chunk.5484.0787bc7d757429828cea.js: 10.12 KB (2.55 KB gzipped)
 - dist/assets/chunk.5565.bbd16270d950a77e4b07.js: 27.82 KB (5.74 KB gzipped)
 - dist/assets/chunk.5608.60dc13bb291ec4931aa6.js: 3.37 KB (1.05 KB gzipped)
 - dist/assets/chunk.5611.e7cc1adbb26b7a91f0d2.js: 44.01 KB (5.61 KB gzipped)
 - dist/assets/chunk.5618.a81d4b72d7a1925a2e9a.js: 29.04 KB (5.48 KB gzipped)
 - dist/assets/chunk.5654.f92721bc16cf2321d4dc.js: 2.01 KB (651 B gzipped)
 - dist/assets/chunk.5682.2a096e85ab9357375568.js: 31.03 KB (5.37 KB gzipped)
 - dist/assets/chunk.5685.7c0d8cd0a3b68d164fa4.js: 20.14 KB (4.03 KB gzipped)
 - dist/assets/chunk.5694.8bb9f285fa1fe63b3dcd.js: 10.94 KB (2.57 KB gzipped)
 - dist/assets/chunk.571.f997f6972838f4347bf7.js: 6.63 KB (2.12 KB gzipped)
 - dist/assets/chunk.5781.872de2f6c99601d48699.js: 30.12 KB (5.45 KB gzipped)
 - dist/assets/chunk.5823.855acd86c602fb2e97ff.js: 21.46 KB (4.96 KB gzipped)
 - dist/assets/chunk.5855.4dde82e1adaffbc3dfc0.js: 17.85 KB (3.6 KB gzipped)
 - dist/assets/chunk.5930.09b6b42955ef31ba0995.js: 3.89 KB (1.47 KB gzipped)
 - dist/assets/chunk.5941.d41f35abf2b886b841f7.js: 16.69 KB (5.91 KB gzipped)
 - dist/assets/chunk.6031.1e2b13c026131c4f23e0.js: 1.61 KB (630 B gzipped)
 - dist/assets/chunk.6034.ea88f32b7969acdcbc96.js: 5.51 KB (1.38 KB gzipped)
 - dist/assets/chunk.6052.187c5d612d99389bfc1f.js: 9.25 KB (2.25 KB gzipped)
 - dist/assets/chunk.6060.3e559b203437a7abbb24.js: 258.27 KB (75.19 KB gzipped)
 - dist/assets/chunk.6083.dd6e079be973b3354ad7.js: 9.92 KB (2.96 KB gzipped)
 - dist/assets/chunk.6089.249256fae482c9e3cd9d.js: 5.95 KB (1.92 KB gzipped)
 - dist/assets/chunk.6111.6622afa7c67487129ca0.js: 27.58 KB (4.62 KB gzipped)
 - dist/assets/chunk.6127.98685c3b4efbdca17ea8.js: 7.92 KB (2.99 KB gzipped)
 - dist/assets/chunk.614.fcdfe5931584bfd3525e.js: 3.85 KB (1.26 KB gzipped)
 - dist/assets/chunk.6159.769f7426496d3074cb5e.js: 3.09 KB (922 B gzipped)
 - dist/assets/chunk.6180.f910ea4371e3e4455c9b.js: 10.73 KB (2.53 KB gzipped)
 - dist/assets/chunk.6230.e87b354fb0c4f0478d37.js: 3.16 KB (1.12 KB gzipped)
 - dist/assets/chunk.6247.99efab8ea129928007e9.js: 17.82 KB (3.13 KB gzipped)
 - dist/assets/chunk.6259.e52df0c3d71525f3e96f.js: 2.81 KB (752 B gzipped)
 - dist/assets/chunk.6270.44f7aa0cb680462a2f65.js: 3.42 KB (1019 B gzipped)
 - dist/assets/chunk.6340.32f3d541ca3b398aa9b5.js: 4.54 KB (1.68 KB gzipped)
 - dist/assets/chunk.6427.161bf837a5a9a8b39aae.js: 18.72 KB (4.46 KB gzipped)
 - dist/assets/chunk.6479.5a40fd3041581597303a.js: 25.48 KB (6.45 KB gzipped)
 - dist/assets/chunk.6548.1e25c8cddd7d626f9033.js: 16.74 KB (2.65 KB gzipped)
 - dist/assets/chunk.6553.4de7ad091f183d5db270.js: 8.41 KB (2.07 KB gzipped)
 - dist/assets/chunk.668.07170e5138748a2dcbb5.js: 5.72 KB (1.74 KB gzipped)
 - dist/assets/chunk.6680.789c82c057fb3067e4eb.js: 16.08 KB (3.11 KB gzipped)
 - dist/assets/chunk.6770.d60648928190487ec4ff.js: 28.17 KB (6.33 KB gzipped)
 - dist/assets/chunk.6799.6ec4e6a557d3e45072de.js: 1015 B (478 B gzipped)
 - dist/assets/chunk.6948.49996141abf184ce36b2.js: 18.43 KB (3.31 KB gzipped)
 - dist/assets/chunk.6956.51a6b7ebb1f919b183d3.js: 5.79 KB (2.34 KB gzipped)
 - dist/assets/chunk.6960.31a20b52049c36aae7de.js: 13.04 KB (2.46 KB gzipped)
 - dist/assets/chunk.7020.5cc1c927bb856a101e32.js: 6.15 KB (1.75 KB gzipped)
 - dist/assets/chunk.7065.0fdf3706b02a8c122253.js: 115.68 KB (23.09 KB gzipped)
 - dist/assets/chunk.7088.2d64d36ded73c79eb0da.js: 3.55 KB (1.07 KB gzipped)
 - dist/assets/chunk.7141.b1ebccdf22977dc07b16.js: 18.3 KB (3.79 KB gzipped)
 - dist/assets/chunk.7216.ac275d5be89cadc239bf.js: 36.91 KB (10.66 KB gzipped)
 - dist/assets/chunk.7317.f43f372fede9826437eb.js: 31.46 KB (4 KB gzipped)
 - dist/assets/chunk.7347.9213765ec4de0bf9659b.js: 52.51 KB (8.55 KB gzipped)
 - dist/assets/chunk.7395.37d103f22965135478da.js: 6.12 KB (1.75 KB gzipped)
 - dist/assets/chunk.7397.1de82f5eb4e2e45d311e.js: 183.16 KB (17.46 KB gzipped)
 - dist/assets/chunk.745.c30aa75376ca7d6e8cf3.js: 13.01 KB (2.75 KB gzipped)
 - dist/assets/chunk.7500.54b52523309f795e59a9.js: 13.84 KB (3.13 KB gzipped)
 - dist/assets/chunk.7590.d41343ff8379237d2347.js: 7.91 KB (2.1 KB gzipped)
 - dist/assets/chunk.760.51647c02b43f80d4cd09.js: 15.81 KB (3.96 KB gzipped)
 - dist/assets/chunk.7612.7a1e9e4f470c686710dd.js: 4.94 KB (1.24 KB gzipped)
 - dist/assets/chunk.7623.6fe6ab6ff356831900ff.js: 14.99 KB (3.38 KB gzipped)
 - dist/assets/chunk.7735.aa2dcc20026ab349ffe8.js: 4.83 KB (1.62 KB gzipped)
 - dist/assets/chunk.7785.1f396c37416adb086041.js: 17.8 KB (3.12 KB gzipped)
 - dist/assets/chunk.7786.87373a62e1151c5890a4.js: 10.02 KB (3.55 KB gzipped)
 - dist/assets/chunk.7820.0a7c7a28ef3015d27ecb.js: 3.97 KB (1.43 KB gzipped)
 - dist/assets/chunk.7841.7b68c9162a080dfdf2a2.js: 25.36 KB (4.36 KB gzipped)
 - dist/assets/chunk.7997.8f391eab55b6b5011e97.js: 33.37 KB (10.9 KB gzipped)
 - dist/assets/chunk.8000.b689e8e505e6c49c1f14.js: 5.44 KB (1.88 KB gzipped)
 - dist/assets/chunk.8013.b67907d299a33820d5fe.js: 22.4 KB (4.02 KB gzipped)
 - dist/assets/chunk.8045.c442e411f142d4fc556f.js: 54.65 KB (8.2 KB gzipped)
 - dist/assets/chunk.8113.4c4b080d4f293fe0d09f.js: 44.58 KB (6.94 KB gzipped)
 - dist/assets/chunk.8182.165f7feb75f7c0d985d9.js: 177.38 KB (17.88 KB gzipped)
 - dist/assets/chunk.8206.5419907f238da5d1731d.js: 32.9 KB (6.28 KB gzipped)
 - dist/assets/chunk.8234.199a28d2332155f657ee.js: 8.63 KB (1.99 KB gzipped)
 - dist/assets/chunk.8271.0ebacfbd060beacf57d1.js: 10.49 KB (1.63 KB gzipped)
 - dist/assets/chunk.829.3ec101cd511e171e105c.js: 6.12 KB (1.48 KB gzipped)
 - dist/assets/chunk.8321.4cdcaad81fa939658a76.js: 72.08 KB (11.42 KB gzipped)
 - dist/assets/chunk.835.4573787db0f7d1a07ac0.js: 12.19 KB (3.75 KB gzipped)
 - dist/assets/chunk.8385.6eca8572f26b2053d263.js: 464.87 KB (142.77 KB gzipped)
 - dist/assets/chunk.8391.56d71266a3b094f3fcfc.js: 3.88 KB (1.67 KB gzipped)
 - dist/assets/chunk.8477.23f0c25a09a17c414709.js: 185.42 KB (17.94 KB gzipped)
 - dist/assets/chunk.8507.d7c6529c251d5b5f650a.js: 14.3 KB (2.86 KB gzipped)
 - dist/assets/chunk.8517.f616fc40d72ed9feada8.js: 11.8 KB (3.21 KB gzipped)
 - dist/assets/chunk.8542.ad926b33654285d6f597.js: 3.3 KB (1.1 KB gzipped)
 - dist/assets/chunk.8560.44000b7948873c77afb8.js: 6.39 KB (1.8 KB gzipped)
 - dist/assets/chunk.8615.d06cbf0c7b1e601d4f27.js: 9.24 KB (3.99 KB gzipped)
 - dist/assets/chunk.8646.b7b3e9cd61a7f038efbb.js: 48.85 KB (10.49 KB gzipped)
 - dist/assets/chunk.8669.184e107cfe16cc304c05.js: 3.51 KB (1.61 KB gzipped)
 - dist/assets/chunk.8683.ce955cae0a75162ac9f6.js: 6.5 KB (1.83 KB gzipped)
 - dist/assets/chunk.8742.4d015a79efc1066a73a2.js: 13.08 KB (2.3 KB gzipped)
 - dist/assets/chunk.8809.8f645d0b22d2cd7fc583.js: 4.98 KB (1.39 KB gzipped)
 - dist/assets/chunk.883.6a5bf7d637914b16ccf3.js: 42.24 KB (7.47 KB gzipped)
 - dist/assets/chunk.8845.7856f36078a3a5aebda5.js: 21.02 KB (4.54 KB gzipped)
 - dist/assets/chunk.8918.30067071020f013ed7f4.js: 1.15 KB (419 B gzipped)
 - dist/assets/chunk.8969.b7206376a98040f6679f.js: 37.81 KB (5.64 KB gzipped)
 - dist/assets/chunk.910.dff0106d1608c15e96d2.js: 10.72 KB (2.26 KB gzipped)
 - dist/assets/chunk.9127.adc34632b379ed500d78.js: 12.08 KB (1.96 KB gzipped)
 - dist/assets/chunk.9142.8a7c159a811888d0946b.js: 17.05 KB (3.56 KB gzipped)
 - dist/assets/chunk.9144.c784c0df1dc4144e5073.js: 94.17 KB (13.24 KB gzipped)
 - dist/assets/chunk.916.9e7845ab1a1063630858.js: 79.01 KB (25.51 KB gzipped)
 - dist/assets/chunk.9173.289082e50c7e32ae2222.js: 9.79 KB (2.29 KB gzipped)
 - dist/assets/chunk.9184.25fafc1f194136b7d9ae.js: 8.66 KB (2.33 KB gzipped)
 - dist/assets/chunk.9217.ce6f151cc5141b0fd6a0.js: 2.15 KB (1.11 KB gzipped)
 - dist/assets/chunk.9298.ba1831e076158013a398.js: 20.88 KB (3.85 KB gzipped)
 - dist/assets/chunk.93.b3ca5920c6208a4deaf9.js: 107.84 KB (28.96 KB gzipped)
 - dist/assets/chunk.9326.0905e03c7e47072a72ff.js: 16.57 KB (4.45 KB gzipped)
 - dist/assets/chunk.9363.c7dabafb2e0be0a05327.js: 28.22 KB (4.88 KB gzipped)
 - dist/assets/chunk.9389.d69775fb7b00ff441b23.js: 7.79 KB (2.77 KB gzipped)
 - dist/assets/chunk.9434.e023c50e8235f7563856.js: 20.56 KB (3.85 KB gzipped)
 - dist/assets/chunk.9581.3779533a0573b9947f6f.js: 2.46 KB (782 B gzipped)
 - dist/assets/chunk.9584.fb397f8b2acf30d9cd97.js: 78.48 KB (26.79 KB gzipped)
 - dist/assets/chunk.9590.82d4b68886b641e6ae40.js: 19.96 KB (7.12 KB gzipped)
 - dist/assets/chunk.9660.f8a1a00db9c25e338ad4.js: 13.41 KB (2.29 KB gzipped)
 - dist/assets/chunk.9675.fc6ce9a1e550f4a46bfc.js: 42.23 KB (7.47 KB gzipped)
 - dist/assets/chunk.9781.a3a0935bf7ea3d228f36.js: 20.86 KB (3.83 KB gzipped)
 - dist/assets/chunk.9927.dd8d5a4fff4d11d70617.js: 607.78 KB (225.61 KB gzipped)
 - dist/assets/chunk.997.a16f7aa831e4d838bb9d.js: 5.31 KB (1.53 KB gzipped)
 - dist/assets/chunk.9997.b84c481d995e63fc3d0c.js: 20.87 KB (3.85 KB gzipped)
 - dist/assets/dummy-d41d8cd98f00b204e9800998ecf8427e.css: 0 B
 - dist/assets/dummy-fab66952736ba48cfdb47f5f1659184b.js: 67.05 KB (8.21 KB gzipped)
 - dist/assets/dummy-fastboot-31c870a0c661d47816598f4746be3aa4.js: 1.75 KB (808 B gzipped)
 - dist/assets/vendor-b081c4d67065b8f7b23bf0e601a8e000.css: 48.87 KB (9.87 KB gzipped)
 - dist/assets/vendor-fc4d0346da795bfcc9e1eff98092feb7.js: 1.09 MB (287.78 KB gzipped)
 - dist/ember-fetch/fetch-fastboot-e28194c4f1288a25de407aad6f7fab09.js: 887 B (510 B gzipped)
```

</details>

<details>
<summary>`npm run build` on main:</summary>

```
Built project successfully. Stored in "dist/".
File sizes:
 - dist/assets/chunk.143.032832f4a161bc262199.js: 2.08 KB (1021 B gzipped)
 - dist/assets/chunk.178.e32bfd28f5168ec3af54.js: 1.52 KB (816 B gzipped)
 - dist/assets/chunk.916.9e7845ab1a1063630858.js: 79.01 KB (25.51 KB gzipped)
 - dist/assets/chunk.958.27b714aa906032f13612.js: 313.16 KB (100.9 KB gzipped)
 - dist/assets/dummy-bb0bd7604c3216530ebd1e4640129494.js: 67.6 KB (8.24 KB gzipped)
 - dist/assets/dummy-d41d8cd98f00b204e9800998ecf8427e.css: 0 B
 - dist/assets/dummy-fastboot-31c870a0c661d47816598f4746be3aa4.js: 1.75 KB (808 B gzipped)
 - dist/assets/vendor-1fa9841096c2b8d78b7e6f637fbb0011.css: 52.11 KB (10.79 KB gzipped)
 - dist/assets/vendor-230036313f8f3ef723c13da10ff1e734.js: 1.15 MB (307.34 KB gzipped)
 - dist/ember-fetch/fetch-fastboot-e28194c4f1288a25de407aad6f7fab09.js: 887 B (510 B gzipped)
```

</details>

So the vendor file size actually went down! And grammars are split into individual chunks. So this is actually an improvement 😄

**Comment by IgnaceMaes** [comment]
Added ribbons as well in `ember-showdown-shikiji` [v0.3.0](https://github.com/IgnaceMaes/ember-showdown-shikiji/releases/tag/ember-showdown-shikiji%400.3.0).

Currently it's made as feature parity to highlight `js`, `ts`, and `hbs`. Added `gjs` and `gts` as well already.

If desired, we can very easily extend this to other languages too as it's now implemented in pure CSS rather than SVG.

**Review by mansona — APPROVED** [review]
LGTM 🎉

**Pull request merged**
